# -*- coding: utf-8 -*-
"""isIsomorphic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrKwyJngyKYnr_2NprwkuJIOw7zLjhFN
"""

def isIsomorphic(s, t):
  if len(s) != len(t):
    return False

  Hash = {}
  Seen = {}

  for i in range(len(s)):
    if s[i] not in Hash:
      if t[i] in Seen:
        return False
      Hash[s[i]] = t[i]
      Seen[t[i]] = s[i]
    elif Hash[s[i]] != t[i]:
      return False
  return True