# -*- coding: utf-8 -*-
"""LengthofLongestSubstring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrKwyJngyKYnr_2NprwkuJIOw7zLjhFN
"""

def lengthOfLongestSubstring(s: str) -> int:
  result = []
  sub = 0
  for i in range(len(s)):
    if s[i] not in result:
      result.append(s[i])
      if sub < len(result):
        sub = len(result)
    else:
      result = result[result.index(s[i]) + 1:]
      result.append(s[i])
  return sub