# -*- coding: utf-8 -*-
"""maxProfit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrKwyJngyKYnr_2NprwkuJIOw7zLjhFN
"""

def maxProfit(prices):
  buy = prices[0]
  profit = 0

  for i in prices[1:]:
    if buy > i:
      buy = i

    profit = max(profit, i - buy)

  return profit