# -*- coding: utf-8 -*-
"""PascalsTriangle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrKwyJngyKYnr_2NprwkuJIOw7zLjhFN
"""

def pascalsTriangle(numRows):
  result = []
  for i in range(numRows):
    result.append([1])
    for j in range(i-1):
      result[-1].append(result[-2][j]+result[-2][j+1])
    if i != 0:
      result[-1].append(1)
  return result